version: "1.0"
stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-plugins/argo-workflow-runner"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    title: Execute unit tests
    image: node:12.18.0
    working_directory: ${{clone}}
    stage: build
    commands:
      - yarn install --dev-dependencies
      - yarn test


  build:
    title: "Building Docker image"
    type: "build"
    image_name: "codefresh/argo-workflow-runner"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    registry: dockerhub
    stage: "build"

  push:
    title: Pushing to Docker Registry
    type: push
    stage: push
    candidate: '${{build}}'
    tag: 'latest'
    registry: dockerhub
    when:
      branch:
        only:
          - main
